export const KEY_UPDATE = "KEY_UPDATE"

// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"

// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_ERROR = "SIGNIN_ERROR"
export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNOUT_ERROR = "SIGNOUT_ERROR"

// RESET PASSWORD
export const RESET_SUCCESS = "RESET_SUCCESS"
export const RESET_ERROR = "RESET_ERROR"

// JOIN ROOM
export const JOIN_SUCCESS = "JOIN_SUCCESS"
export const LEAVE_SUCCESS = "LEAVE_SUCCESS"